version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "appadoption"
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "danielmorais774@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "7070:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge